CREATE DATABASE DADOS_VOO;

CREATE EXTERNAL TABLE EXPLORACAO_FAIXA_ATRASO_PARTIDA (
    FIM_DE_SEMANA_PARTIDA_PREVISTA BOOLEAN,
    NOME_EMPRESA STRING,
    NOME_MES_PARTIDA_REAL STRING,
    NOME_AEROPORTO_ORIGEM STRING,
    DIA_DA_SEMANA_PARTIDA_PREVISTA STRING,
    FAIXA_ATRASO_PARTIDA STRING,
    TOTAL_OCORRENCIAS INT
)
PARTITIONED BY (
    CODIGO_TIPO_LINHA VARCHAR(1),
    MES_PARTIDA_REAL TINYINT,
    INDICE_SEMANA_PARTIDA_PREVISTA TINYINT,
    UF_AEROPORTO_ORIGEM VARCHAR(2),
    CIDADE_AEROPORTO_ORIGEM STRING,
    SIGLA_ICAO_AEROPORTO_ORIGEM VARCHAR(15),
    SIGLA_ICAO_EMPRESA_AEREA VARCHAR(25)
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|'
STORED AS TEXTFILE;


CREATE EXTERNAL TABLE EXPLORACAO_FAIXA_ATRASO_CHEGADA (
    NUMERO_VOO BOOLEAN,
    NOME_AEROPORTO_DESTINO STRING,
    NOME_EMPRESA STRING,
    MES_CHEGADA_PREVISTA INT,
    NOME_MES_CHEGADA_PREVISTA STRING,
    TOTAL_OCORRENCIAS INT, 
    DIA_DA_SEMANA_CHEGADA_REAL STRING,
    DIA_DA_SEMANA_CHEGADA_PREVISTA STRING,
    FAIXA_ATRASO_CHEGADA STRING,
    SITUACAO_VOO STRING, 
    NOME_MES_CHEGADA_REAL STRING
    
)
PARTITIONED BY (
    CODIGO_TIPO_LINHA VARCHAR(1),
    MES_CHEGADA_REAL TINYINT,
    INDICE_SEMANA_PARTIDA_PREVISTA TINYINT,
    UF_AEROPORTO_DESTINO VARCHAR(2),
    CIDADE_AEROPORTO_DESTINO STRING,
    SIGLA_ICAO_AEROPORTO_DESTINO VARCHAR(15),
    SIGLA_ICAO_EMPRESA_AEREA VARCHAR(25)
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|'
STORED AS TEXTFILE;

LOAD DATA LOCAL INPATH '/home/rodrigo/Documentos/projetos/dados_voos/data/processed/exploracao_faixa_atraso_partida/exploracao_faixa_atraso_partida_KLM.csv'
INTO TABLE EXPLORACAO_FAIXA_ATRASO_PARTIDA
IGNORE 1 LINES;



SELECT *
FROM exploracao_faixa_atraso_partida 
where sigla_icao_empresa_aerea = 'AZU';

SELECT *
from exploracao_faixa_atraso_chegada efac ;


DESCRIBE FORMATTED exploracao_faixa_atraso_partida;

DROP DATABASE dados_voos;
SHOW PARTITIONS exploracao_faixa_atraso_partida;

