CREATE DATABASE DADOS_VOO;

CREATE EXTERNAL TABLE EXPLORACAO_FAIXA_ATRASO_PARTIDA (
    FIM_DE_SEMANA_PARTIDA_PREVISTA BOOLEAN,
    NOME_EMPRESA STRING,
    NOME_MES_PARTIDA_REAL STRING,
    NOME_AEROPORTO_ORIGEM STRING,
    DIA_DA_SEMANA_PARTIDA_PREVISTA STRING,
    FAIXA_ATRASO_PARTIDA STRING,
    TOTAL_OCORRENCIAS INT
)
PARTITIONED BY (
    CODIGO_TIPO_LINHA VARCHAR(1),
    MES_PARTIDA_REAL TINYINT,
    INDICE_SEMANA_PARTIDA_PREVISTA TINYINT,
    UF_AEROPORTO_ORIGEM VARCHAR(2),
    CIDADE_AEROPORTO_ORIGEM STRING,
    SIGLA_ICAO_AEROPORTO_ORIGEM VARCHAR(15),
    SIGLA_ICAO_EMPRESA_AEREA VARCHAR(25)
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|'
STORED AS TEXTFILE;

LOAD DATA LOCAL INPATH '/home/rodrigo/Documentos/projetos/dados_voos/data/processed/exploracao_faixa_atraso_partida/exploracao_faixa_atraso_partida_KLM.csv'
INTO TABLE EXPLORACAO_FAIXA_ATRASO_PARTIDA
IGNORE 1 LINES;

CREATE EXTERNAL TABLE total_votos_candidato (
	NR_CANDIDATO INT,
	NM_CANDIDATO STRING,
	NM_URNA_CANDIDATO STRING,
	DS_SIT_TOT_TURNO STRING,
	TOTAL_VOTOS_CANDIDATO_CIDADE INT,
	TOTAL_VOTOS_CIDADE INT,
	PERCENTUAL_VOTOS_CIDADE FLOAT
) PARTITIONED BY (
	ANO_ELEICAO INT,
	CD_CARGO INT,
	CD_MUNICIPIO INT,
	CD_SIT_TOT_TURNO INT
) ROW FORMAT DELIMITED
 FIELDS TERMINATED BY '|'
STORED AS TEXTFILE;

SELECT *
FROM exploracao_faixa_atraso_partida 
where sigla_icao_empresa_aerea = 'GEC';


DESCRIBE FORMATTED exploracao_faixa_atraso_partida;

DROP DATABASE dados_voos;
SHOW PARTITIONS exploracao_faixa_atraso_partida;

